services:
  node-app:
    image: book-library-backend-node-app:latest
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:test101@postgres:5432/library?schema=public
    command: npm run start
