services:
  nginx:
    image: nginx:1.17.9
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-app
  node-app:
    deploy:
        replicas: 3
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
      - /app/generated
    ports:
      - :80
    environment:
      - PORT=80
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test101
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - nodejs_basic_postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  nodejs_basic_postgres_data:
